# Generated by Django 5.0.3 on 2024-03-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogentry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
