# Generated by Django 5.0.3 on 2024-03-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogentry_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью'),
        ),
    ]
